In [ ]:
# this model is used to predict whether based on the data a student will pass or fail

## IMPORTING DATASET

In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\goura\Downloads\Student_Performance.csv")

In [3]:
df.head()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f


## PREPROCESSING THE DATA
the task asks us to predict whether a student will pass or fail based on the number of hours he/she studies,attendence and marks.
so this dataset needs to be minimised and preprocessed.

In [4]:
# selecting a handful of columns columns 
df = df[['student_id', 'study_hours', 'attendance_percentage', 'overall_score', 'final_grade']]

In [5]:
df.head()

,student_id,study_hours,attendance_percentage,overall_score,final_grade
0,1,3.1,84.3,53.1,e
1,2,3.7,87.8,61.3,d
2,3,7.9,65.5,89.6,b
3,4,1.1,58.1,41.6,e
4,5,1.3,61.0,25.4,f


we are trying to predict pass or fail but the final grade columns has ranges varying from a-f, so
i think its better to leave F as 0 and  then try to classify the rest as 1 (a-e) 

In [6]:
df['final_grade'] = df['final_grade'].replace('f', 0)
df['final_grade'] = df['final_grade'].replace(['a','b','c','d','e'], 1)

C:\Users\goura\AppData\Local\Temp\ipykernel_16908\2189868038.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['final_grade'] = df['final_grade'].replace(['a','b','c','d','e'], 1)


In [7]:
df.head()

,student_id,study_hours,attendance_percentage,overall_score,final_grade
0,1,3.1,84.3,53.1,1
1,2,3.7,87.8,61.3,1
2,3,7.9,65.5,89.6,1
3,4,1.1,58.1,41.6,1
4,5,1.3,61.0,25.4,0


In [8]:
print(df)

       student_id  study_hours  attendance_percentage  overall_score  \
0               1          3.1                   84.3           53.1   
1               2          3.7                   87.8           61.3   
2               3          7.9                   65.5           89.6   
3               4          1.1                   58.1           41.6   
4               5          1.3                   61.0           25.4   
...           ...          ...                    ...            ...   
24995       12047          1.8                   55.2           46.1   
24996        1102          2.7                   97.1           56.5   
24997        4422          1.0                   63.0           36.7   
24998        7858          1.0                   69.4           34.1   
24999       11621          0.7                   60.3           31.4   

       final_grade  
0                1  
1                1  
2                1  
3                1  
4                0  
...      

In [9]:
# taking data as input and output
inp=df.iloc[:,:4]
out=df.iloc[:,4:]

In [10]:
out.head()

,final_grade
0,1
1,1
2,1
3,1
4,0


## train-test split
splitting the data for training and testing and scaling them

In [11]:
from sklearn.model_selection import train_test_split as tts
inp_tr,inp_te,out_tr,out_te=tts(inp,out,test_size=0.3)

In [12]:
out_tr

,final_grade
7748,1
10408,1
17324,1
7616,1
22968,1
...,...
22813,1
19378,1
9305,1
6084,1


## SCALING

In [13]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
inp_tr=ss.fit_transform(inp_tr)

In [14]:
inp_tr

array([[ 0.06675561,  1.13872678, -1.57460112,  0.57303544],
       [ 0.68148848,  0.30662154,  1.23574777,  0.76834765],
       [-0.18838165,  0.86135836,  0.93662648,  0.75779023],
       ...,
       [ 0.42658233, -0.20188722, -1.67198945, -0.7466416 ],
       [-0.3177991 ,  0.49153381,  1.22183516,  0.48329741],
       [ 1.40091083, -1.17267667, -1.5606885 , -1.43815237]],
      shape=(17500, 4))

In [15]:
inp_te=ss.fit_transform(inp_te)

## MODEL TRAINING
using KNN and logistic regression for this dataset

In [16]:
from sklearn.linear_model import LogisticRegression
BP=LogisticRegression()
BP.fit(inp_tr,out_tr)

C:\Users\goura\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(inp_tr,out_tr)

C:\Users\goura\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


## TESTING

In [18]:
BP.predict(inp_te)

array([1, 1, 0, ..., 1, 1, 1], shape=(7500,))

In [19]:
knn.predict(inp_te)

array([1, 1, 0, ..., 1, 1, 1], shape=(7500,))

In [20]:
from sklearn.metrics import accuracy_score as acs
BPT=BP.predict(inp_te)
KNNT=knn.predict(inp_te)
acs1=acs(BPT,out_te)
acs2=acs(KNNT,out_te)
print(BPT)
print(KNNT)
print(acs1)
print(acs2)

[1 1 0 ... 1 1 1]
[1 1 0 ... 1 1 1]
0.9949333333333333
0.9893333333333333


In [22]:
print(BP.coef_)

[[ 0.09925222  0.79956294  0.26027287 18.65968166]]


## VISUALIZATION

In [35]:
from sklearn.metrics import confusion_matrix
CM1=confusion_matrix(out_te,BPT)
CM2=confusion_matrix(out_te,KNNT)
print(CM1)
print(CM2)


[[ 874   17]
 [   2 6607]]
[[ 847   44]
 [  28 6581]]


## model packaging

In [ ]:
import pickle
